name: CI
on:
  push:
    branches: [ master ]
    
  workflows_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Testing the package
        run: |
          go get 
          go test ./...